# Generated by Django 4.1.3 on 2022-11-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('interpreters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interpreters',
            new_name='Interpreter',
        ),
    ]
