# Generated by Django 4.1.3 on 2022-11-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreters', '0002_rename_interpreters_interpreter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpreter',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
